name: Python Tests Contact

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get install -y wget unzip
        
    - name: Install Chrome for Testing and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
        # Устанавливаем Chrome for Testing (рекомендуемый способ для автоматизации)
        CHROME_VERSION="140.0.7339.207"
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chrome-linux64.zip"
        unzip -q chrome-linux64.zip -d chrome-for-testing
        sudo mv chrome-for-testing/chrome-linux64 /opt/chrome-for-testing
        
        # Устанавливаем соответствующий ChromeDriver
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
        unzip -q chromedriver-linux64.zip -d chromedriver
        sudo mv chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
    - name: Verify installations
      run: |
        echo "=== Chrome for Testing ==="
        /opt/chrome-for-testing/chrome --version
        echo "=== ChromeDriver ==="
        chromedriver --version
        echo "=== ChromeDriver Path ==="
        which chromedriver
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AutoTest/requirements.txt
        pip install pytest pytest-html
        pip install pytest-xdist

    - name: Install stability packages
      run: |
        pip install pytest-rerunfailures pytest-timeout

    - name: Run tests with retries
      run: |
        cd /home/runner/work/GitHub_Actions/GitHub_Actions
        cp -r ./AutoTest/Pages .
        python -m pytest AutoTest/Test-Prog/test_Negative.py \
          -v \
          --html=report.html \
          --self-contained-html \
          --reruns 3 \
          --reruns-delay 1 \
          --timeout=120
    
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: |
          report.html
        retention-days: 30
